### ISSUE TITLE
Fill in user information

### ISSUE THREAD

**Issue by hahtml** [MangoKiwi/TeachTech#8]
List user information and upload file if he or she wants to be a teacher

**Comment by AdrianFeng** [comment]
支持在此基础上补充添加
**common**

first name
last name
email 
gender 
    **student**   
       interested subjects 
       
   **Teacher**
       uploaded courses
       uploaded file

**Comment by hahtml** [comment]
1. user entity:
username; firstname; lastname; gender; location(city); birth_date; degree; current_role(either student or teacher);
2. student entity:
key: user_id;
attribute:  appointment; tag
3. teacher entity:
key: user_id;
attribute:  diploma_file; resume_file; appointment; available_time_array; tag; rating(int); count
4. appointment entity:
key: (user_id, user_id)
attribute: date; status(completed or not); rating
5. comment entity:
key: (user_id, user_id)
attribute: comment; date
6. tag entity:
key: user_id
attribute: content

**Comment by AdrianFeng** [comment]
student 的 comment 是 list of comment？还有 history 是什么？

**Comment by hahtml** [comment]
teacher和student的comment都能删掉，history就是之前上过的课记录
